# environment.yml
name: tatortot
channels: !!python/tuple
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'digitalglobe'
- !!python/unicode
  'defaults'
dependencies:
- conda-forge::pip
- conda-forge::python=3.6
- conda-forge::numpy>=1.15.4,<1.16
- conda-forge::pandas>=0.23.4,<0.24
- conda-forge::boto3>=1.9.90,<2.0
- conda-forge::rasterio>=1.0.18,<2.0
- conda-forge::fiona>=1.8.6,<2.0
- conda-forge::shapely>=1.6.4,<2.0
- conda-forge::pyproj>=1.9.6,<2.0
- conda-forge::tqdm>=4.30,<5.0
- conda-forge::scipy>=1.2.0,<1.3.0
- conda-forge::scikit-image>=0.14,<0.16
- conda-forge::jupyter
- conda-forge::matplotlib>=3
- conda-forge::nb_conda_kernels
- pip:
  - tinytools<=1.1.0
  - awscli>=1.16.100,<2.0
  - utm==0.4.2
  - click>=7.0,<8.0
